### ISSUE TITLE
On peut se voir dans la semaine ?...

### ISSUE THREAD

**Issue by klevron** [VincentEchavidre/webdocCCFD#1]
Vu qu'on ne s'est pas vu ce matin...

**Comment by VincentEchavidre** [comment]
Désolé pour hier, notre emploi du temps a été un peu chamboulé et nous avons oublié de passer (nous devions avoir une réunion mais elle a été annulée à la dernière minute)
Quel jour vous irait le mieux ?

**Comment by klevron** [comment]
Pas de soucis, passez si possible en fin de matinée (vers 11h45), si je ne suis pas dans mon bureau on essaye de se voir lundi matin prochain.
